CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Cinemas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Address" character varying(200) NOT NULL,
        "City" character varying(50),
        CONSTRAINT "PK_Cinemas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Genres" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Movies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(100) NOT NULL,
        "Description" text,
        "Duration" integer NOT NULL,
        "BasePrice" numeric(5,2) NOT NULL,
        "Rating" integer,
        "ReleaseDate" timestamp with time zone,
        CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "PersonTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PricePercentDiscount" numeric(5,2) NOT NULL DEFAULT 0.0,
        "Name" text NOT NULL,
        CONSTRAINT "PK_PersonTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "ProjectionTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PriceAmountDiscount" numeric(5,2) NOT NULL DEFAULT 0.0,
        "Name" text NOT NULL,
        CONSTRAINT "PK_ProjectionTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "SeatTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PriceAmountDiscount" numeric(5,2) NOT NULL DEFAULT 0.0,
        "Name" text NOT NULL,
        CONSTRAINT "PK_SeatTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserType" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "Email" text NOT NULL,
        "PasswordHash" text,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Rooms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "CinemaId" integer NOT NULL,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rooms_Cinemas" FOREIGN KEY ("CinemaId") REFERENCES "Cinemas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "MovieGenres" (
        "GenresId" integer NOT NULL,
        "MoviesId" integer NOT NULL,
        CONSTRAINT "PK_MovieGenres" PRIMARY KEY ("GenresId", "MoviesId"),
        CONSTRAINT "FK_MovieGenres_Genres_GenresId" FOREIGN KEY ("GenresId") REFERENCES "Genres" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieGenres_Movies_MoviesId" FOREIGN KEY ("MoviesId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Screenings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone,
        "Language" text,
        "BasePrice" numeric(5,2) NOT NULL,
        "ProjectionTypeId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        "MovieId" integer NOT NULL,
        CONSTRAINT "PK_Screenings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Screenings_Movies" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Screenings_ProjectionTypes" FOREIGN KEY ("ProjectionTypeId") REFERENCES "ProjectionTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Screenings_Rooms" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Seats" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Row" text NOT NULL,
        "Number" integer NOT NULL,
        "SeatTypeId" integer NOT NULL,
        "RoomId" integer NOT NULL,
        CONSTRAINT "PK_Seats" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Seats_Rooms" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Seats_SeatTypes" FOREIGN KEY ("SeatTypeId") REFERENCES "SeatTypes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Bookings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingStatus" integer NOT NULL,
        "BookingTime" timestamp with time zone NOT NULL,
        "UserId" integer NOT NULL,
        "ScreeningId" integer NOT NULL,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_Screenings" FOREIGN KEY ("ScreeningId") REFERENCES "Screenings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Bookings_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE TABLE "Tickets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PersonTypeId" integer NOT NULL,
        "TotalPrice" numeric(5,2) NOT NULL,
        "BookingId" integer NOT NULL,
        "SeatId" integer NOT NULL,
        "ScreeningId" integer NOT NULL,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tickets_Bookings" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tickets_PersonType" FOREIGN KEY ("PersonTypeId") REFERENCES "PersonTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tickets_Screenings_ScreeningId" FOREIGN KEY ("ScreeningId") REFERENCES "Screenings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tickets_Seat" FOREIGN KEY ("SeatId") REFERENCES "Seats" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_ScreeningId" ON "Bookings" ("ScreeningId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_UserId" ON "Bookings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_MovieGenres_MoviesId" ON "MovieGenres" ("MoviesId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Rooms_CinemaId" ON "Rooms" ("CinemaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Screenings_MovieId" ON "Screenings" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Screenings_ProjectionTypeId" ON "Screenings" ("ProjectionTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Screenings_RoomId" ON "Screenings" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Seats_RoomId" ON "Seats" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Seats_SeatTypeId" ON "Seats" ("SeatTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_BookingId" ON "Tickets" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_PersonTypeId" ON "Tickets" ("PersonTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_ScreeningId" ON "Tickets" ("ScreeningId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tickets_SeatId" ON "Tickets" ("SeatId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125135108_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251125135108_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

